spring:
    application:
        name: the-cowboyday-API
    config:
        import: optional:file:.env[.properties]

    datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true

jwt:
    session:
        expiration-minutes: ${JWT_EXPIRATION_MINUTES_SESSION:10}
    refresh:
        expiration-minutes: ${JWT_EXPIRATION_MINUTES_REFRESH:7200}
        
rsa:
    public-key: classpath:certs/public.pem
    private-key: classpath:certs/private.pem